name: Deploy Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: "npm"
      - run: npm ci
      - name: Log in with Azure
        uses: azure/login@v1
        with:
          creds: "${{ secrets.AZURE_CREDENTIALS }}"
      - name: Populate Dev Environment Variables
        run: source env/load-app-config.sh --name apigee-hackathon-ac --export-type github
      - name: Build
        run: ./node_modules/.bin/nx affected --target=build --configuration production --base=$NX_BASE
      - name: Deploy
        run: ./node_modules/.bin/nx affected --target=deploy --base=$NX_BASE
