name: Integration Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2
      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"
          export_default_credentials: true
      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v0"
      - name: "Use gcloud CLI"
        run: "gcloud info"
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: "npm"
      - run: npm ci
      - run: npm i -D @swc/core-linux-x64-gnu
      - name: Build
        run: ./node_modules/.bin/nx affected --target=build --configuration production --base=$NX_BASE

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: "npm"
      - run: npm ci
      - run: npm i -D @swc/core-linux-x64-gnu
      - name: Lint
        run: ./node_modules/.bin/nx affected --target=lint --base=$NX_BASE

  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2
      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"
          export_default_credentials: true
      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v0"
      - name: "Use gcloud CLI"
        run: "gcloud info"
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: "npm"
      - run: npm ci
      - run: npm i -D @swc/core-linux-x64-gnu
      - name: "Installing Firebase Tools"
        run: npm install -g firebase-tools
      - name: Log in with Azure
        uses: azure/login@v1
        with:
          creds: "${{ secrets.AZURE_CREDENTIALS }}"
          export_default_credentials: true
      - name: Populate Dev Environment Variables
        run: source env/load-app-config.sh --name apigee-hackathon-ac --export-type github --include-local true
      - name: Unit Tests
        run: firebase emulators:exec --only firestore --project hackathon-apigee-portal './node_modules/.bin/nx affected --target=test --base=$NX_BASE'
        env:
          PROJECT_ID: "hackathon-apigee-portal"
          GCLOUD_PROJECT: "hackathon-apigee-portal"
          GOOGLE_CLOUD_PROJECT: "hackathon-apigee-portal"
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
          FIREBASE_TOKEN: ${{ secrets.GCP_CREDENTIALS }}
          FIREBASE_USE_EMULATOR: true
          FIREBASE_AUTH_EMULATOR_HOST: "localhost:9021"
          FIRESTORE_EMULATOR_HOST: "localhost:9022"
          FIREBASE_DATABASE_EMULATOR_HOST: "localhost:9023"
          PUBSUB_EMULATOR_HOST: "localhost:9024"
          FIREBASE_STORAGE_EMULATOR_HOST: "localhost:9025"
          FIREBASE_FUNCTIONS_EMULATOR_HOST: "localhost:5001"
          DISABLE_PUBSUB_AUTH: true
          NX_USE_EMULATORS: true
          NX_AUTH_EMULATOR_HOST: "localhost:9021"
          GATSBY_USE_EMULATORS: true
          GATSBY_FIREBASE_AUTH_EMULATOR_HOST: "localhost:9021"

  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2
      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"
          export_default_credentials: true
      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v0"
      - name: "Use gcloud CLI"
        run: "gcloud info"
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: "npm"
      - run: npm ci
      - run: npm i -D @swc/core-linux-x64-gnu
      - name: Log in with Azure
        uses: azure/login@v1
        with:
          creds: "${{ secrets.AZURE_CREDENTIALS }}"
          export_default_credentials: true
      - name: Populate Dev Environment Variables
        run: source env/load-app-config.sh --name apigee-hackathon-ac --export-type github
      - name: Integration Tests
        run: ./node_modules/.bin/nx affected --target=integration-test --base=$NX_BASE

  end-to-end-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2
      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"
          export_default_credentials: true
      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v0"
      - name: "Use gcloud CLI"
        run: "gcloud info"
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: "npm"
      - run: npm ci
      - run: npm i -D @swc/core-linux-x64-gnu
      - name: Log in with Azure
        uses: azure/login@v1
        with:
          creds: "${{ secrets.AZURE_CREDENTIALS }}"
          export_default_credentials: true
      - name: Populate Dev Environment Variables
        run: source env/load-app-config.sh --name apigee-hackathon-ac --export-type github
      - name: End To End Tests
        run: ./node_modules/.bin/nx affected --target=e2e --base=$NX_BASE
